### ISSUE TITLE
Investigate if we can use existing ubuntu base images

### ISSUE THREAD

**Issue by richardcase** [weaveworks/image-builder#3]
Currently, we are using debootstrap or the Ubuntu Cloud Image raw file to create our base images (see [here](https://github.com/weaveworks/flintlock/blob/main/docs/image-creation.md).

We need to investigate if we can build a suitable base image using the existing ubuntu base images published on docker hub. This was initially tried but failed due to lack of init system. So we will need to add this.

**Comment by richardcase** [comment]
A few resources that may be helpful:

https://iximiuz.com/en/posts/from-docker-container-to-bootable-linux-disk-image/

And the corresponding project:

https://iximiuz.com/en/posts/from-docker-container-to-bootable-linux-disk-image/

**Comment by richardcase** [comment]
Important soon

**Comment by yitsushi** [comment]
@richardcase : Is it still valid?
